service: product-service

provider: 
  name: aws
  runtime: nodejs16.x
  region: eu-north-1
  stage: dev

plugins:
  - serverless-esbuild
  - serverless-auto-swagger

custom:
  esbuild:
    config: './esbuild.config.js'
  autoswagger:
    basePath: '/dev'
    host: 'm3a8z91udj.execute-api.eu-north-1.amazonaws.com'

functions:
  getProductsList:
    handler: getProductsList/handler.handler
    events:
      - http:
          path: products
          method: get
          cors: true
  getProductsById:
    handler: getProductsById/handler.handler
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
