service: import-service

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-north-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - 's3:*'
      Resource:
        - 'arn:aws:s3:::import-service-bucket-zafar/*'

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: true

functions:
  importProductFiles:
    handler: handler.importProductFiles
    events: 
      - http:
          path: import
          method: get 
          cors: true
          request:
            parameters:
              querystrings:
                name: true