service: import-service

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-north-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - 's3:*'
      Resource:
        - 'arn:aws:s3:::import-service-bucket-zafar/*'
    - Effect: Allow
      Action: 
        - 'sqs:*'
      Resource:
        - 'arn:aws:sqs:eu-north-1:301382425986:catalogItemsQueue'

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: true

functions:
  importProductFiles:
    handler: handler.importProductsFile
    events: 
      - http:
          path: import
          method: get 
          cors: true
          authorizer:
            name: basicAuthorizer
            type: token
            arn: "arn:aws:lambda:eu-north-1:301382425986:function:authorization-service-dev-basicAuthorizer"
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: import-service-bucket-zafar
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
