service: import-service

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-north-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - 's3:*'
        - 'sqs:*'
      Resource:
        - 'arn:aws:s3:::import-service-bucket-zafar/*'
        - 'arn:aws:sqs:::catalogItemsQueue/*'

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: true

functions:
  importProductFiles:
    handler: handler.importProductsFile
    events: 
      - http:
          path: import
          method: get 
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: import-service-bucket-zafar
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
